# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-11 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SLA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('service', models.CharField(max_length=500)),
                ('penalty', models.IntegerField()),
                ('price', models.IntegerField()),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('agreedAt', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.IntegerField()),
                ('performanceLevel', models.IntegerField()),
                ('operator', models.IntegerField()),
                ('sla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sla.SLA')),
            ],
        ),
    ]
